package project1;

import static project1.Project1.output;

public class GUI extends javax.swing.JFrame {

    public static int nom_instructions = 0;
    public static int count = 0;

    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        r0 = new javax.swing.JButton();
        at = new javax.swing.JButton();
        v0 = new javax.swing.JButton();
        v1 = new javax.swing.JButton();
        a0 = new javax.swing.JButton();
        a1 = new javax.swing.JButton();
        a2 = new javax.swing.JButton();
        a3 = new javax.swing.JButton();
        t0 = new javax.swing.JButton();
        t1 = new javax.swing.JButton();
        t2 = new javax.swing.JButton();
        t3 = new javax.swing.JButton();
        t4 = new javax.swing.JButton();
        t5 = new javax.swing.JButton();
        t6 = new javax.swing.JButton();
        t7 = new javax.swing.JButton();
        s0 = new javax.swing.JButton();
        s1 = new javax.swing.JButton();
        s2 = new javax.swing.JButton();
        s3 = new javax.swing.JButton();
        s4 = new javax.swing.JButton();
        s5 = new javax.swing.JButton();
        s6 = new javax.swing.JButton();
        s7 = new javax.swing.JButton();
        t8 = new javax.swing.JButton();
        t9 = new javax.swing.JButton();
        k0 = new javax.swing.JButton();
        k1 = new javax.swing.JButton();
        gp = new javax.swing.JButton();
        sp = new javax.swing.JButton();
        fp = new javax.swing.JButton();
        ra = new javax.swing.JButton();
        Run = new javax.swing.JButton();
        Zero = new javax.swing.JButton();
        One = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        Addi = new javax.swing.JButton();
        Nor = new javax.swing.JButton();
        Sll = new javax.swing.JButton();
        Slt = new javax.swing.JButton();
        Lb = new javax.swing.JButton();
        Sw = new javax.swing.JButton();
        Sb = new javax.swing.JButton();
        Beq = new javax.swing.JButton();
        Slti = new javax.swing.JButton();
        jump = new javax.swing.JButton();
        Jal = new javax.swing.JButton();
        Enter = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        InputArea = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        OutputArea = new javax.swing.JTextArea();
        Lw = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Jr = new javax.swing.JButton();
        RType = new javax.swing.JButton();
        LBU = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        no_instructions = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtInstruction = new javax.swing.JTextField();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mips Simulation");

        r0.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        r0.setLabel("$0");
        r0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r0ActionPerformed(evt);
            }
        });

        at.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        at.setText("$at");
        at.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atActionPerformed(evt);
            }
        });

        v0.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        v0.setText("$v0");
        v0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v0ActionPerformed(evt);
            }
        });

        v1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        v1.setText("$v1");
        v1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v1ActionPerformed(evt);
            }
        });

        a0.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        a0.setText("$a0");
        a0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a0ActionPerformed(evt);
            }
        });

        a1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        a1.setText("$a1");
        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });

        a2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        a2.setText("$a2");
        a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a2ActionPerformed(evt);
            }
        });

        a3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        a3.setText("$a3");
        a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a3ActionPerformed(evt);
            }
        });

        t0.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        t0.setText("$t0");
        t0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t0ActionPerformed(evt);
            }
        });

        t1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        t1.setText("$t1");
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });

        t2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        t2.setText("$t2");
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });

        t3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        t3.setText("$t3");
        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });

        t4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        t4.setText("$t4");
        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });

        t5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        t5.setText("$t5");
        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });

        t6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        t6.setText("$t6");
        t6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6ActionPerformed(evt);
            }
        });

        t7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        t7.setText("$t7");
        t7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t7ActionPerformed(evt);
            }
        });

        s0.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        s0.setText("$s0");
        s0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s0ActionPerformed(evt);
            }
        });

        s1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        s1.setText("$s1");
        s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1ActionPerformed(evt);
            }
        });

        s2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        s2.setText("$s2");
        s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s2ActionPerformed(evt);
            }
        });

        s3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        s3.setText("$s3");
        s3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s3ActionPerformed(evt);
            }
        });

        s4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        s4.setText("$s4");
        s4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s4ActionPerformed(evt);
            }
        });

        s5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        s5.setText("$s5");
        s5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s5ActionPerformed(evt);
            }
        });

        s6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        s6.setText("$s6");
        s6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s6ActionPerformed(evt);
            }
        });

        s7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        s7.setText("$s7");
        s7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s7ActionPerformed(evt);
            }
        });

        t8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        t8.setText("$t8");
        t8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t8ActionPerformed(evt);
            }
        });

        t9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        t9.setText("$t9");
        t9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t9ActionPerformed(evt);
            }
        });

        k0.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        k0.setText("$k0");
        k0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k0ActionPerformed(evt);
            }
        });

        k1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        k1.setText("$k1");
        k1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k1ActionPerformed(evt);
            }
        });

        gp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        gp.setText("$gp");
        gp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpActionPerformed(evt);
            }
        });

        sp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sp.setText("$sp");
        sp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spActionPerformed(evt);
            }
        });

        fp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        fp.setText("$fp");
        fp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fpActionPerformed(evt);
            }
        });

        ra.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ra.setText("$ra");
        ra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raActionPerformed(evt);
            }
        });

        Run.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Run.setText("Run");
        Run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunActionPerformed(evt);
            }
        });

        Zero.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Zero.setText("0");
        Zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZeroActionPerformed(evt);
            }
        });

        One.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        One.setText("1");
        One.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OneActionPerformed(evt);
            }
        });

        Add.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Addi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Addi.setText("Addi");
        Addi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddiActionPerformed(evt);
            }
        });

        Nor.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Nor.setText("Nor");
        Nor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NorActionPerformed(evt);
            }
        });

        Sll.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Sll.setText("Sll");
        Sll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SllActionPerformed(evt);
            }
        });

        Slt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Slt.setText("Slt");
        Slt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SltActionPerformed(evt);
            }
        });

        Lb.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Lb.setText("Lb");
        Lb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LbActionPerformed(evt);
            }
        });

        Sw.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Sw.setText("Sw");
        Sw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SwActionPerformed(evt);
            }
        });

        Sb.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Sb.setText("Sb");
        Sb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SbActionPerformed(evt);
            }
        });

        Beq.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Beq.setText("beq");
        Beq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeqActionPerformed(evt);
            }
        });

        Slti.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Slti.setText("Slti");
        Slti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SltiActionPerformed(evt);
            }
        });

        jump.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jump.setText("J");
        jump.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumpActionPerformed(evt);
            }
        });

        Jal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Jal.setText("JAL");
        Jal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JalActionPerformed(evt);
            }
        });

        Enter.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Enter.setText("Enter");
        Enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterActionPerformed(evt);
            }
        });

        InputArea.setEditable(false);
        InputArea.setColumns(20);
        InputArea.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        InputArea.setRows(5);
        jScrollPane2.setViewportView(InputArea);

        OutputArea.setEditable(false);
        OutputArea.setColumns(20);
        OutputArea.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        OutputArea.setRows(5);
        jScrollPane4.setViewportView(OutputArea);

        Lw.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Lw.setText("Lw");
        Lw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LwActionPerformed(evt);
            }
        });

        Delete.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Jr.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Jr.setText("Jr");
        Jr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JrActionPerformed(evt);
            }
        });

        RType.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RType.setText("R-type");
        RType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RTypeActionPerformed(evt);
            }
        });

        LBU.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LBU.setText("Lbu");
        LBU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LBUActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField1.setText(" Number of instructions:");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField2.setText("     Enter Address:");

        no_instructions.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        no_instructions.setText("0");
        no_instructions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_instructionsActionPerformed(evt);
            }
        });

        txtAddress.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtAddress.setText("0");
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setText("Enter your instructions:");

        txtInstruction.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtInstruction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInstructionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Sll, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(Slt, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(Lb, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(Sw, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(Addi, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(Nor, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(Add, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(Lw, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jump, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Jal, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Sb, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Beq, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Slti, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(Jr, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(RType, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBU, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(r0, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(at, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(v0, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(v1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(a0, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(a1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(a2, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(a3, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t0, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(s6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(s5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(s4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(s3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(s2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(s1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(s0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(s7, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(t9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(k0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(k1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(gp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(fp, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Run, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(One, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Zero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(123, 123, 123)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(76, 76, 76))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(86, 86, 86)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(no_instructions, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtInstruction, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(Enter, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(no_instructions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInstruction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Enter)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r0, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t0, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s0, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Zero, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(at, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(One, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Addi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Beq, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(v0, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(k0, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Slti, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(v1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(k1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Sll, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jump, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a0, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Slt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lw, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jr, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBU, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Sw, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(RType, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ra, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(s7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(a3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(Run, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Registers
    private void r0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r0ActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "00000");
    }//GEN-LAST:event_r0ActionPerformed

    private void v0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v0ActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "00010");
    }//GEN-LAST:event_v0ActionPerformed

    private void t0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t0ActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "01000");
    }//GEN-LAST:event_t0ActionPerformed

    private void s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s2ActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "10010");
    }//GEN-LAST:event_s2ActionPerformed

    private void atActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "00001");
    }//GEN-LAST:event_atActionPerformed

    private void v1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v1ActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "00011");
    }//GEN-LAST:event_v1ActionPerformed

    private void a0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a0ActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "00100");
    }//GEN-LAST:event_a0ActionPerformed

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "00101");
    }//GEN-LAST:event_a1ActionPerformed

    private void a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a2ActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "00110");
    }//GEN-LAST:event_a2ActionPerformed

    private void a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a3ActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "00111");
    }//GEN-LAST:event_a3ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "01001");
    }//GEN-LAST:event_t1ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "01010");
    }//GEN-LAST:event_t2ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "01011");
    }//GEN-LAST:event_t3ActionPerformed

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "01100");
    }//GEN-LAST:event_t4ActionPerformed

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "01101");
    }//GEN-LAST:event_t5ActionPerformed

    private void t6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t6ActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "01110");
    }//GEN-LAST:event_t6ActionPerformed

    private void t7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t7ActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "01111");
    }//GEN-LAST:event_t7ActionPerformed

    private void s0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s0ActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "10000");
    }//GEN-LAST:event_s0ActionPerformed

    private void s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1ActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "10001");
    }//GEN-LAST:event_s1ActionPerformed

    private void s3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s3ActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "10011");
    }//GEN-LAST:event_s3ActionPerformed

    private void s4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s4ActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "10100");
    }//GEN-LAST:event_s4ActionPerformed

    private void s5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s5ActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "10101");
    }//GEN-LAST:event_s5ActionPerformed

    private void s6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s6ActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "10110");
    }//GEN-LAST:event_s6ActionPerformed

    private void s7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s7ActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "10111");
    }//GEN-LAST:event_s7ActionPerformed

    private void t8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t8ActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "11000");
    }//GEN-LAST:event_t8ActionPerformed

    private void t9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t9ActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "11001");
    }//GEN-LAST:event_t9ActionPerformed

    private void k0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k0ActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "11010");
    }//GEN-LAST:event_k0ActionPerformed

    private void k1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k1ActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "11011");
    }//GEN-LAST:event_k1ActionPerformed

    private void gpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "11100");
    }//GEN-LAST:event_gpActionPerformed

    private void spActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "11101");
    }//GEN-LAST:event_spActionPerformed

    private void fpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fpActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "11110");
    }//GEN-LAST:event_fpActionPerformed

    private void raActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "11111");
    }//GEN-LAST:event_raActionPerformed

    //INSTRUCTIONS
    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "100000");

    }//GEN-LAST:event_AddActionPerformed

    private void AddiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddiActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "001000");
    }//GEN-LAST:event_AddiActionPerformed

    private void NorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NorActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "001000");
    }//GEN-LAST:event_NorActionPerformed

    private void SllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SllActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "000000");
    }//GEN-LAST:event_SllActionPerformed

    private void SltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SltActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "101010");
    }//GEN-LAST:event_SltActionPerformed

    private void LwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LwActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "100011");
    }//GEN-LAST:event_LwActionPerformed

    private void LbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LbActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "100000");
    }//GEN-LAST:event_LbActionPerformed

    private void LBUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LBUActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "100100");
    }//GEN-LAST:event_LBUActionPerformed

    private void SwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SwActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "101011");
    }//GEN-LAST:event_SwActionPerformed

    private void SbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SbActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "101000");
    }//GEN-LAST:event_SbActionPerformed

    private void BeqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeqActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "000100");
    }//GEN-LAST:event_BeqActionPerformed

    private void SltiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SltiActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "001010");
    }//GEN-LAST:event_SltiActionPerformed

    private void jumpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumpActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "000010");
    }//GEN-LAST:event_jumpActionPerformed

    private void JalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JalActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "000011");
    }//GEN-LAST:event_JalActionPerformed

    private void JrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JrActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "001000");
    }//GEN-LAST:event_JrActionPerformed

    private void RTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RTypeActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "000000");
    }//GEN-LAST:event_RTypeActionPerformed

    private void ZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZeroActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "0");
    }//GEN-LAST:event_ZeroActionPerformed

    private void OneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OneActionPerformed
        txtInstruction.setText(txtInstruction.getText() + "1");
    }//GEN-LAST:event_OneActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        txtInstruction.setText("");
    }//GEN-LAST:event_DeleteActionPerformed

    private void EnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterActionPerformed

        instruct_mem.instruct_arr[count] = txtInstruction.getText();
        InputArea.setText(InputArea.getText() + (count + 1) + "- " + txtInstruction.getText() + "\n");
        txtInstruction.setText("");
        count++;

    }//GEN-LAST:event_EnterActionPerformed

    private void RunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunActionPerformed
        nom_instructions = Integer.parseInt(no_instructions.getText().trim());
        PC.address = Integer.parseInt(txtAddress.getText());
        int clock = 1;
        Memory.init();
        while (PC.address <= ((nom_instructions - 1) * 4)) {
            OutputArea.setText(OutputArea.getText() + " Clock Cycle " + clock + " is : \n");
            Instruction.codes(instruct_mem.instruct_arr[(PC.address) / 4]);
            output();

            OutputArea.setText(OutputArea.getText() + "  Wires: \n");
            OutputArea.setText(OutputArea.getText() + "  ------------ \n");
            OutputArea.setText(OutputArea.getText() + "  PC output: " + Project1.real_offset + "\n");
            OutputArea.setText(OutputArea.getText() + "  PC+4 adder output : " + (Project1.real_offset + 4) + "\n");
            OutputArea.setText(OutputArea.getText() + "  Instruction Memory Output: " + Instruction.Finstruct + "\n");
            OutputArea.setText(OutputArea.getText() + "  Opcode field of instruction: " + ALU.b_to_dec(Instruction.op_code) + "\n");
            OutputArea.setText(OutputArea.getText() + "  Rs field of instruction: " + ALU.b_to_dec(Instruction.rs) + "\n");
            OutputArea.setText(OutputArea.getText() + "  Rt field of instruction: " + ALU.b_to_dec(Instruction.rt) + "\n");
            OutputArea.setText(OutputArea.getText() + "  Rd field of instruction: " + ALU.b_to_dec(Instruction.rd) + "\n");
            OutputArea.setText(OutputArea.getText() + "  RegDestination Mux output: " + ALU.b_to_dec(Muxes.MuxOut) + "\n");
            OutputArea.setText(OutputArea.getText() + "  Offset field of instruction: " + Instruction.constant + "\n");
            OutputArea.setText(OutputArea.getText() + "  Sign-extender Output: " + Sign_Extend.s + "\n");
            OutputArea.setText(OutputArea.getText() + "  Shift-2 output: " + ALU_Branch.SHIFT + "\n");
            OutputArea.setText(OutputArea.getText() + "  Target address adder: " + PC.address + "\n");
            OutputArea.setText(OutputArea.getText() + "  Function code of instruction: " + ALU.b_to_dec(Instruction.fun_code) + "\n");
            OutputArea.setText(OutputArea.getText() + "  Read data 1: " + ALU.RS + "\n");
            OutputArea.setText(OutputArea.getText() + "  Read data 2: " + ALU.RT + "\n");
            OutputArea.setText(OutputArea.getText() + "  ALU second input: " + ALU.second_data + "\n");
            OutputArea.setText(OutputArea.getText() + "  ALU output: " + ALU.valueofALU + "\n");
            OutputArea.setText(OutputArea.getText() + "  Zero flag:" + ALU.zeroflag + "\n");
            if ((Control_Unit.Memread.equals("0") && Control_Unit.MemWrite.equals("0") || Control_Unit.MemWrite.equals("1"))) {
                OutputArea.setText(OutputArea.getText() + "  Data memory output: UNKNOWN " + "\n");
            } else if (Control_Unit.Memread.equals("1")) {
                OutputArea.setText(OutputArea.getText() + "  Data memory output: " + Memory.d + "\n");
            }

            OutputArea.setText(OutputArea.getText() + "  MemtoReg Mux output: " + Memory.d + "\n");
            OutputArea.setText(OutputArea.getText() + "  PC input: " + PC.address + "\n");
            OutputArea.setText(OutputArea.getText() + "  AND gate output: " + Mux_branch.ANDgate + "\n");
            OutputArea.setText(OutputArea.getText() + "----------------------------------------------------- \n");
            OutputArea.setText(OutputArea.getText() + "  Control Unit Signals: " + "\n");
            OutputArea.setText(OutputArea.getText() + "  ----------------------------\n");
            OutputArea.setText(OutputArea.getText() + "  RegDest: " + Control_Unit.Regdst + "\n");
            OutputArea.setText(OutputArea.getText() + "  Branch: " + Control_Unit.Branch + "\n");
            OutputArea.setText(OutputArea.getText() + "  MemRead: " + Control_Unit.Memread + "\n");
            OutputArea.setText(OutputArea.getText() + "  MemtoReg: " + Control_Unit.Memtoreg + "\n");
            OutputArea.setText(OutputArea.getText() + "  ALUOp: " + Control_Unit.ALUOp + "\n");
            OutputArea.setText(OutputArea.getText() + "  MemWrite: " + Control_Unit.MemWrite + "\n");
            OutputArea.setText(OutputArea.getText() + "  ALUSrc: " + Control_Unit.ALUSrc + "\n");
            OutputArea.setText(OutputArea.getText() + "  RegWrite: " + Control_Unit.RegWrite + "\n");
            OutputArea.setText(OutputArea.getText() + "  ALU control output: " + ALU_Control.function + "\n");
            OutputArea.setText(OutputArea.getText() + "---------------------------------------------------- \n");

            clock++;

            //Registers
            OutputArea.setText(OutputArea.getText() + "  Register File: \n" + "  --------------------- \n");
            for (int i = 0; i < 32; i++) {

                OutputArea.setText(OutputArea.getText() + "  " + reg_file.regnames[i] + " : ");
                OutputArea.setText(OutputArea.getText() + reg_file.regsfile[i] + "\n");

            }
            OutputArea.setText(OutputArea.getText() + "---------------------------------------------------- \n");
        }
        //Memory    
        OutputArea.setText(OutputArea.getText() + "  Memory: \n" + "  ------------------- \n");

        if (Control_Unit.MemWrite.equals("1")) {
            for (int i = 0; i < Memory.List.length; i++) {
                if (i == ALU.valueofALU) {
                    if (Instruction.op_code.equals("101011")) {
                        String memory = Memory.Extend(Memory.List[i].length(), Memory.List[i]);
                        OutputArea.setText(OutputArea.getText() + "  Address: " + (i));
                        OutputArea.setText(OutputArea.getText() + "  Value: " + (int) ALU.convert(memory) + "\n");
                        memory = Memory.Extend(Memory.List[i + 1].length(), Memory.List[i + 1]);
                        OutputArea.setText(OutputArea.getText() + "  Address: " + (i + 1));
                        OutputArea.setText(OutputArea.getText() + "  Value: " + (int) ALU.convert(memory) + "\n");
                        memory = Memory.Extend(Memory.List[i + 2].length(), Memory.List[i + 2]);
                        OutputArea.setText(OutputArea.getText() + "  Address: " + (i + 2));
                        OutputArea.setText(OutputArea.getText() + "  Value: " + (int) ALU.convert(memory) + "\n");
                        memory = Memory.Extend(Memory.List[i + 3].length(), Memory.List[i + 3]);
                        OutputArea.setText(OutputArea.getText() + "  Address: " + (i + 3));
                        OutputArea.setText(OutputArea.getText() + "  Value: " + (int) ALU.convert(memory) + "\n");

                    } else if (Instruction.op_code.equals("101000")) {
                        String memory = Memory.Extend(Memory.List[i].length(), Memory.List[i]);
                        OutputArea.setText(OutputArea.getText() + "  Address: " + (i));
                        OutputArea.setText(OutputArea.getText() + "  Value: " + (int) ALU.convert(memory) + "\n");
                    }
                }
            }
        } else {
            OutputArea.setText(OutputArea.getText() + "Nothing changes ");
        }

        Run.setEnabled(false);
        no_instructions.setEnabled(false);
        txtAddress.setEnabled(false);
        txtInstruction.setEnabled(false);
        Enter.setEnabled(false);
    }//GEN-LAST:event_RunActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void no_instructionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_instructionsActionPerformed

    }//GEN-LAST:event_no_instructionsActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed

    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtInstructionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInstructionActionPerformed

    }//GEN-LAST:event_txtInstructionActionPerformed

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Addi;
    private javax.swing.JButton Beq;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Enter;
    private javax.swing.JTextArea InputArea;
    private javax.swing.JButton Jal;
    private javax.swing.JButton Jr;
    private javax.swing.JButton LBU;
    private javax.swing.JButton Lb;
    private javax.swing.JButton Lw;
    private javax.swing.JButton Nor;
    private javax.swing.JButton One;
    private javax.swing.JTextArea OutputArea;
    private javax.swing.JButton RType;
    private javax.swing.JButton Run;
    private javax.swing.JButton Sb;
    private javax.swing.JButton Sll;
    private javax.swing.JButton Slt;
    private javax.swing.JButton Slti;
    private javax.swing.JButton Sw;
    private javax.swing.JButton Zero;
    private javax.swing.JButton a0;
    private javax.swing.JButton a1;
    private javax.swing.JButton a2;
    private javax.swing.JButton a3;
    private javax.swing.JButton at;
    private javax.swing.JButton fp;
    private javax.swing.JButton gp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton jump;
    private javax.swing.JButton k0;
    private javax.swing.JButton k1;
    private javax.swing.JTextField no_instructions;
    private javax.swing.JButton r0;
    private javax.swing.JButton ra;
    private javax.swing.JButton s0;
    private javax.swing.JButton s1;
    private javax.swing.JButton s2;
    private javax.swing.JButton s3;
    private javax.swing.JButton s4;
    private javax.swing.JButton s5;
    private javax.swing.JButton s6;
    private javax.swing.JButton s7;
    private javax.swing.JButton sp;
    private javax.swing.JButton t0;
    private javax.swing.JButton t1;
    private javax.swing.JButton t2;
    private javax.swing.JButton t3;
    private javax.swing.JButton t4;
    private javax.swing.JButton t5;
    private javax.swing.JButton t6;
    private javax.swing.JButton t7;
    private javax.swing.JButton t8;
    private javax.swing.JButton t9;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtInstruction;
    private javax.swing.JButton v0;
    private javax.swing.JButton v1;
    // End of variables declaration//GEN-END:variables

}
